title: Dunman High School
url: https://dunmanhigh.moe.edu.sg
favicon: /images/Dunman High School.png
colors:
  primary-color: "#03095c"
  secondary-color: "#d0021b"
  media-colors:
    - title: media-color-one
      color: "#310b7d"
    - title: media-color-two
      color: "#f5a623"
    - title: media-color-three
      color: "#f8e71c"
    - title: media-color-four
      color: "#076d19"
    - title: media-color-five
      color: "#cc2262"
resources_name: campus life
description: |-
  To Care • To Serve • To Lead 
  关怀 • 服务 • 引领
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://ogp-dunman-staging.netlify.app
prod: https://ogp-dunman-prod.netlify.app
shareicon: /images/Homepage/dhs.jpg
is_government: false
facebook-pixel: ""
google_analytics: ""
linkedin-insights: ""
